=== NadzeyaParkhimovich/TATJAVA01_2017_Task05_Nadzeya_Parkhimovich/bin/com/epam/xmlparsers/menuType.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/menuType" xmlns:tns="http://www.example.org/menuType" elementFormDefault="qualified">
	<element name="menu">
		<complexType>
			<sequence>
				<element name="type" type="tns:Type" minOccurs="1"  maxOccurs="3" />
			</sequence>
		</complexType>
	</element>
	<complexType name="Type">
		<sequence>
			<element name="food" type="tns:Food" minOccurs="1"  maxOccurs="unbounded" />
		</sequence>
		<attribute name="id" type="string" use="required" />
	</complexType>
	<complexType name="Food">
		<sequence>
			<element name="name" type="string" />
			<element name="description" type="string" />
			<element name="weight">
				<simpleType>
					<restriction base="int">
						<minInclusive value="1"/>
					</restriction>
				</simpleType>
			</element>
		</sequence>
		<attribute name="id" type="int" use="required" />
	</complexType>
</schema>

=== NadzeyaParkhimovich/TATJAVA01_2017_Task05_Nadzeya_Parkhimovich/src/com/epam/xmlparsers/menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<menu  xmlns="http://www.example.org/menuType" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/menuType menuType.xsd">
	<type id="coldSnacks">
		<food id="C1">
			<name>Ассорти рыбное</name>
			<description>Слабосоленая форель, семга</description>
			<weight>100/20/15</weight>
			<price></price>
		</food>
		<food id="C2">
			<name>Тарталетки с красной икрой</name>
			<description>Тарталетки с красной икрой</description>
			<weight>60/50</weight>
			<price></price>
		</food>
		<food id="C3">
			<name>Бастурма</name>
			<description>Вяленая вырезка из говяжьего мяса</description>
			<weight>50/5</weight>
			<price></price>
		</food>
		<food id="C4">
			<name>Брынза</name>
			<description>Рассольный сыр</description>
			<weight>75/5</weight>
			<price></price>
		</food>
	</type>
	<type id="hotSnacks">
		<food id="H1">
			<name>Лобио с шампиньонами</name>
			<description>Фасоль с шампиньонами и грецким орехом</description>
			<weight>150/5</weight>
			<price>105</price>
		</food>
		<food id="H2">
			<name>Жульен</name>
			<description>1. с курицей</description>
			<weight>120/1</weight>
			<price>165</price>
		</food>
	</type>
	<type id="breakfast">
		<food id="B1">
			<name>Глазунья</name>
			<description>2 яйца</description>
			<weight>150</weight>
			<price></price>
		</food>
		<food id="B2">
			<name>Омлет</name>
			<description></description>
			<weight>100</weight>
			<price></price>
		</food>
		<food id="B3">
			<name>Блинчики с мясом</name>
			<description>Жареные блинчики с мясом</description>
			<weight>150</weight>
			<price></price>
		</food>
	</type>
</menu>
